//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpjavacsharp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Service/", ConfigurationName="ServiceReference1.ServiceCercle")]
    public interface ServiceCercle {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/ServiceCercle/CalculerSurfaceRequest", ReplyAction="http://Service/ServiceCercle/CalculerSurfaceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        tpjavacsharp.ServiceReference1.CalculerSurfaceResponse CalculerSurface(tpjavacsharp.ServiceReference1.CalculerSurfaceRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/ServiceCercle/CalculerPerimetreRequest", ReplyAction="http://Service/ServiceCercle/CalculerPerimetreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        tpjavacsharp.ServiceReference1.CalculerPerimetreResponse CalculerPerimetre(tpjavacsharp.ServiceReference1.CalculerPerimetreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service/")]
    public partial class cercle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double rayonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double rayon {
            get {
                return this.rayonField;
            }
            set {
                this.rayonField = value;
                this.RaisePropertyChanged("rayon");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculerSurface", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class CalculerSurfaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tpjavacsharp.ServiceReference1.cercle arg0;
        
        public CalculerSurfaceRequest() {
        }
        
        public CalculerSurfaceRequest(tpjavacsharp.ServiceReference1.cercle arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculerSurfaceResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class CalculerSurfaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public CalculerSurfaceResponse() {
        }
        
        public CalculerSurfaceResponse(double @return) {
            this.@return = @return;
            //
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculerPerimetre", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class CalculerPerimetreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tpjavacsharp.ServiceReference1.cercle arg0;
        
        public CalculerPerimetreRequest() {
        }
        
        public CalculerPerimetreRequest(tpjavacsharp.ServiceReference1.cercle arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculerPerimetreResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class CalculerPerimetreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public CalculerPerimetreResponse() {
        }
        
        public CalculerPerimetreResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCercleChannel : tpjavacsharp.ServiceReference1.ServiceCercle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCercleClient : System.ServiceModel.ClientBase<tpjavacsharp.ServiceReference1.ServiceCercle>, tpjavacsharp.ServiceReference1.ServiceCercle {
        
        public ServiceCercleClient() {
        }
        
        public ServiceCercleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCercleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCercleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCercleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tpjavacsharp.ServiceReference1.CalculerSurfaceResponse tpjavacsharp.ServiceReference1.ServiceCercle.CalculerSurface(tpjavacsharp.ServiceReference1.CalculerSurfaceRequest request) {
            return base.Channel.CalculerSurface(request);
        }
        
        public double CalculerSurface(tpjavacsharp.ServiceReference1.cercle arg0) {
            tpjavacsharp.ServiceReference1.CalculerSurfaceRequest inValue = new tpjavacsharp.ServiceReference1.CalculerSurfaceRequest();
            inValue.arg0 = arg0;
            tpjavacsharp.ServiceReference1.CalculerSurfaceResponse retVal = ((tpjavacsharp.ServiceReference1.ServiceCercle)(this)).CalculerSurface(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tpjavacsharp.ServiceReference1.CalculerPerimetreResponse tpjavacsharp.ServiceReference1.ServiceCercle.CalculerPerimetre(tpjavacsharp.ServiceReference1.CalculerPerimetreRequest request) {
            return base.Channel.CalculerPerimetre(request);
        }
        
        public double CalculerPerimetre(tpjavacsharp.ServiceReference1.cercle arg0) {
            tpjavacsharp.ServiceReference1.CalculerPerimetreRequest inValue = new tpjavacsharp.ServiceReference1.CalculerPerimetreRequest();
            inValue.arg0 = arg0;
            tpjavacsharp.ServiceReference1.CalculerPerimetreResponse retVal = ((tpjavacsharp.ServiceReference1.ServiceCercle)(this)).CalculerPerimetre(inValue);
            return retVal.@return;
        }
    }
}
